#!/bin/bash

if [ -z $1 ]
then
	echo "No file provided"
	exit 1
fi
if [[ -z $2 ]]
then
    mount_dest=./mnt
else
    mount_dest="$2"
fi

uid=$(id -u $USER)
gid=$(id -g $USER)

device=$(sudo losetup -f)

sudo losetup $device $1 && \
sudo tcplay -m $1 -d $device && \
sudo mount -o nodev,nosuid,uid=$uid,gid=$gid /dev/mapper/$1 $mount_dest
