#!/bin/bash 

# input file name:
[[ -z $1 ]] && echo "No file provided" && exit 1
file_name=$1
# specify mount dest if not provided:
if [[ -z $2 ]]
then
    mount_dest=./mnt
else
    mount_dest="$2"
fi

uid=$(id -u $USER)
gid=$(id -g $USER)

sudo umount "$mount_dest"

losetup_devices_to_remove=$(losetup | grep $file_name | awk '{print $1}')
for i in $losetup_devices_to_remove; do sudo losetup -d $i; done

dm_setup_devices_to_remove=$(sudo dmsetup ls | sort | grep $file_name | awk '{print $1}')
for i in $dm_setup_devices_to_remove; do sudo dmsetup remove $i; done

