#!/bin/bash -e

# input file name:
[[ -z $1 ]] && echo "No file provided" && exit 1
# specify mount dest if not provided:
if [[ -z $2 ]]
then
    mount_dest=./mnt
else
    mount_dest="$2"
fi

uid=$(id -u $USER)
gid=$(id -g $USER)
device=/dev/loop0

sudo umount "$mount_dest"
sudo losetup -d $device
sudo dmsetup remove $1
devices_to_remove=$(sudo dmsetup ls | sort | grep $1 | awk '{print $1}')
for i in $devices_to_remove; do sudo dmsetup remove $i; done

